spring:
  application:
    name: "eventarz-portal"
  data:
    neo4j:
      uri: "bolt://18.222.117.2:7687"
      username: "neo4j"
      password: "i-0fb5191d82a056e60"
  cloud.loadbalancer.ribbon.enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true