spring:
  application.name: "eventarz-zuul-proxy"
  cloud.loadbalancer.ribbon.enabled: false
server:
  port: 8082
  use-forward-headers: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  debug.request: true
  add-proxy-headers: true
  sensitive-headers:
  routes:
    application:
      path: /**
      serviceId: eventarz-application

      # TODO: Try org.springframework.cloud.netflix.zuul.filters.post.LocationRewriteFilter
      # TODO: Or the freshest Stack Overflow link in "Praca magisterska"