#Default local configuration

spring:
  application.name: "eventarz-zuul-proxy"
  cloud.loadbalancer.ribbon.enabled: false

server:
  port: 8083
  use-forward-headers: true
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/eventarz.p12
    key-store-password: password
    key-alias: eventarz
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

ribbon:
  ReadTimeout: 60000

zuul:
  ignoredServices: '*'
  debug.request: true
  add-proxy-headers: true
  sensitive-headers:
  routes:
    eventarz-application:
      path: /**
      serviceId: eventarz-application

eventarz-application.ribbon.NFLoadBalancerRuleClassName: com.agh.EventarzZuulZerver.StickySessionRule

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: debug